import type { Post } from "../../utils/types";

export const posts: Post[] = [
  {
    id: 1,
    title: "Unlocking Business Efficiency with SaaS Solutions",
    description: "Discover how modern cloud-based software is transforming traditional workflows and driving growth.",
    category: "Business",
    type: "Guide",
    year: "2024",
    author: "Jennifer Taylor",
    readTime: "8 min read",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=1000",
    content: [
      { type: "paragraph", text: "The shift toward Software as a Service (SaaS) isn't just a trend; it's a fundamental restructuring." },
      { type: "heading", text: "Why Efficiency Matters Now" },
      { type: "paragraph", text: "In a post-digital world, speed is the ultimate currency." },
      { type: "list", items: ["Reduced Upfront Costs", "Automatic Updates", "Global Accessibility"] }
    ]
  },
  {
    id: 2,
    title: "Revolutionizing industries through SaaS implementation",
    description: "A deep dive into industry-specific transformations from healthcare to manufacturing.",
    category: "Tech",
    type: "Case Study",
    year: "2024",
    author: "Marcus Chen",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=1000",
    content: [{ type: "paragraph", text: "SaaS is the engine of the Fourth Industrial Revolution." }]
  },
  {
    id: 3,
    title: "The Future of Generative AI in Creative Workflows",
    description: "How AI is moving from a novelty tool to a core component of the designer's toolkit.",
    category: "AI",
    type: "Analysis",
    year: "2024",
    author: "Elena Rossi",
    readTime: "10 min read",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=1000",
    content: [{ type: "paragraph", text: "Generative AI is redefining what it means to be a creator." }]
  },
  {
    id: 4,
    title: "Scaling Engineering Teams: Lessons from Silicon Valley",
    description: "The organizational challenges of growing from 10 to 100 developers without losing velocity.",
    category: "Dev",
    type: "Guide",
    year: "2023",
    author: "David Vark",
    readTime: "12 min read",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=1000",
    content: [{ type: "paragraph", text: "Scaling isn't just about hiring; it's about communication." }]
  },
  {
    id: 5,
    title: "Minimalism in Modern Dashboard Design",
    description: "Why less is often more when it comes to complex data visualization.",
    category: "Design",
    type: "Opinion",
    year: "2024",
    author: "Sarah Jenkins",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1551288049-bbbda536639a?auto=format&fit=crop&q=80&w=1000",
    content: [{ type: "paragraph", text: "Complexity is the enemy of clarity in dashboard design." }]
  },
  {
    id: 6,
    title: "Mastering UI Elements: A Practical Guide for Designers",
    description: "Dive into the world of user interfaces with our expert guides for buttons and cards.",
    category: "Design",
    type: "Tutorial",
    year: "2024",
    author: "Jennifer Taylor",
    readTime: "3 min read",
    image: "https://images.unsplash.com/photo-1542744094-24638eff58bb?auto=format&fit=crop&q=80&w=1000",
    content: [{ type: "paragraph", text: "A great UI is invisible and intuitive." }]
  },
  {
    id: 7,
    title: "Crafting Seamless Experiences: The Art of Intuitive UI",
    description: "Explore the principles and techniques that drive user-centric UI design.",
    category: "UX Research",
    type: "Research",
    year: "2024",
    author: "Jennifer Taylor",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&q=80&w=1000",
    content: [{ type: "paragraph", text: "Intuition is the result of following established mental models." }]
  },
  {
    id: 8,
    title: "Beyond Aesthetics: The Power of Emotional UX Design",
    description: "Discover how incorporating empathy and psychology impacts user retention.",
    category: "Psychology",
    type: "Feature",
    year: "2024",
    author: "Ryan A.",
    readTime: "2 min read",
    image: "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?auto=format&fit=crop&q=80&w=1000",
    content: [{ type: "paragraph", text: "Designing for the 'lows' is as important as the 'highs'." }]
  },
  {
    id: 9,
    title: "The Rise of Zero-Config Deployment Tools",
    description: "How Vercel and Netlify changed the way we ship code to production.",
    category: "Dev",
    type: "Trends",
    year: "2024",
    author: "Alex Rivers",
    readTime: "7 min read",
    image: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&q=80&w=1000",
    content: [{ type: "paragraph", text: "The DevOps barrier is lowering for every developer." }]
  },
  {
    id: 10,
    title: "Sustainable SaaS: Reducing Carbon Footprints",
    description: "Strategies for optimizing code and server usage for environmental impact.",
    category: "Tech",
    type: "Analysis",
    year: "2023",
    author: "Mia Wong",
    readTime: "9 min read",
    image: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&q=80&w=1000",
    content: [{ type: "paragraph", text: "Green computing is no longer a niche concern." }]
  },
  {
    id: 11,
    title: "Security by Design in Enterprise Applications",
    description: "Integrating security protocols into the earliest stages of development.",
    category: "Business",
    type: "Guide",
    year: "2024",
    author: "Marcus Chen",
    readTime: "11 min read",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=1000",
    content: [{ type: "paragraph", text: "Security is a process, not a product." }]
  },
  {
    id: 12,
    title: "The Death of the Hamburguer Menu?",
    description: "Evaluating the pros and cons of traditional navigation in mobile apps.",
    category: "UX Research",
    type: "Opinion",
    year: "2024",
    author: "Sarah Jenkins",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&q=80&w=1000",
    content: [{ type: "paragraph", text: "Users are tired of hiding their navigation." }]
  },
  {
    id: 13,
    title: "Edge Computing and the Future of Latency",
    description: "Why moving logic closer to the user is the next step for high-performance apps.",
    category: "Tech",
    type: "Research",
    year: "2024",
    author: "Alex Rivers",
    readTime: "8 min read",
    image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&q=80&w=1000",
    content: [{ type: "paragraph", text: "Latency is the silent killer of user experience." }]
  },
  {
    id: 14,
    title: "Psychology of Dark Patterns in E-Commerce",
    description: "Identifying and avoiding unethical design practices that trick users.",
    category: "Psychology",
    type: "Case Study",
    year: "2023",
    author: "Elena Rossi",
    readTime: "10 min read",
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&q=80&w=1000",
    content: [{ type: "paragraph", text: "Ethics in design is a long-term competitive advantage." }]
  },
  {
    id: 15,
    title: "TypeScript 5.x: What Developers Need to Know",
    description: "A summary of the most impactful features for enterprise developers.",
    category: "Dev",
    type: "Tutorial",
    year: "2024",
    author: "David Vark",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&q=80&w=1000",
    content: [{ type: "paragraph", text: "TypeScript is evolving faster than ever." }]
  },
  {
    id: 16,
    title: "Building accessible React Components",
    description: "A guide to WAI-ARIA and semantic HTML for modern web frameworks.",
    category: "Design",
    type: "Guide",
    year: "2024",
    author: "Mia Wong",
    readTime: "9 min read",
    image: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&q=80&w=1000",
    content: [{ type: "paragraph", text: "Accessibility is not a feature; it's a right." }]
  },
  {
    id: 17,
    title: "The State of No-Code in 2024",
    description: "Can visual builders truly replace traditional development for startups?",
    category: "SaaS",
    type: "Trends",
    year: "2024",
    author: "Alex Rivers",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1454165833767-02a698d1316a?auto=format&fit=crop&q=80&w=1000",
    content: [{ type: "paragraph", text: "No-code is reaching its maturation point." }]
  },
  {
    id: 18,
    title: "Effective Onboarding for SaaS Users",
    description: "The first five minutes of a user's experience determine their lifetime value.",
    category: "Business",
    type: "Analysis",
    year: "2024",
    author: "Jennifer Taylor",
    readTime: "7 min read",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=80&w=1000",
    content: [{ type: "paragraph", text: "Onboarding is the most critical part of the funnel." }]
  },
  {
    id: 19,
    title: "Color Theory in Product Branding",
    description: "How choosing the right palette can drive emotional connection to your brand.",
    category: "Design",
    type: "Feature",
    year: "2023",
    author: "Elena Rossi",
    readTime: "8 min read",
    image: "https://images.unsplash.com/photo-1505330622279-bf7d7fc918f4?auto=format&fit=crop&q=80&w=1000",
    content: [{ type: "paragraph", text: "Color is the first thing a user perceives." }]
  },
  {
    id: 20,
    title: "Mastering the Art of Technical Writing",
    description: "How to explain complex systems to both engineers and stakeholders.",
    category: "Dev",
    type: "Tutorial",
    year: "2024",
    author: "Marcus Chen",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&q=80&w=1000",
    content: [{ type: "paragraph", text: "Writing is a core skill for every senior engineer." }]
  }
];